spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
server:
  context-path: /choosepaper
druid:
  datasource:
    url: jdbc:mysql://localhost:3306/choosepaper?characterEncoding=utf8&tinyInt1isBit=false
    username: cbuser
    password: cbpass
mybatis:
  config: classpath:mybatis-config.xml
